### ISSUE TITLE
Problem in "Create New Visualization"

### ISSUE THREAD

**Issue by hatakelolo** [formtools/module-data_visualization#1]
Hi, i have no problem installing the module in formtools, but can't create visualizations, i click in the button and nothing happens. ¿The module still work with google api? Thanks

**Comment by pourfallah** [comment]
the problem is php load failure that make javascript error.
the problem can fix by edit this lines:
```
g.quicklinks_dialog_width = {$module_settings["quicklinks_dialog_width"]};
g.quicklinks_dialog_height = {$module_settings["quicklinks_dialog_height"]};
g.vis_tile_size = {$module_settings["quicklinks_dialog_thumb_size"]};
```
that's located in `index.php` file.
you must put your configs in that lines.

**Comment by pourfallah** [comment]
you must change the folder name of this module to `data_visualization` before install it. this make module installer make correctly.

**Comment by hatakelolo** [comment]
Thank you so much, now it works properly.

**Comment by benkeen** [comment]
Sorry about the confusion with the folder names.  I've updated all the README's on all repos to include a link to the installation instructions. That page mentions you need to rename the folder names.
