### ISSUE TITLE
Client permissions to view visualizations not functioning

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-data_visualization#11]
As administrator I can see the visualizations, but when I log in as the client who has permissions to view these visualizations (for all views) they are not present to view.
![image](https://user-images.githubusercontent.com/12632568/37945460-5a12cbb8-314e-11e8-9933-0150f150dc8f.png)

**Comment by johnbleck3** [comment]
when I log in as the client who has that permission to view these visualizations, the option to view is not present.
![image](https://user-images.githubusercontent.com/12632568/37945640-24c8d780-314f-11e8-811b-77a216650e23.png)

**Comment by benkeen** [comment]
Thanks, @johnbleck3! Appreciate the QA. :) I'll take a look.

**Comment by benkeen** [comment]
This has been fixed in 2.0.7 - I'll add the new version to the site shortly.
