### ISSUE TITLE
SQLSTATE Message when adding Activity Chart

### ISSUE THREAD

**Issue by tidalfire** [formtools/module-data_visualization#12]
![image](https://user-images.githubusercontent.com/11295884/38363022-e61a03d2-38ca-11e8-9914-e04eb42c02b6.png)

General Error: 1364 when clicking Create Visualization to create Activity Chart. 

3.0.0-beta-20180320 and DV module 2.0.7.

Localhost install for testing. All modules/code updated.

T

**Comment by benkeen** [comment]
Thanks @tidalfire. I vaguely remember fixing this issue, and trying it out tonight I can't seem to reproduce it. Are you running 3.0.0 final now? Mind testing this again?

**Comment by tidalfire** [comment]
Ben,

1. Tried 3.0 final on WAMP64 install and got same result and error.

2. Installed XAMMP to check local environment and Visualization Activity and charts **WORKED** first time.

3. Then did “**live**” hosted install and all **OK** as well.

So must be local environment related.!!

4. HOWEVER, during **both** WAMP and XAMMP local install of Form Tools 3.0 final I received the message below (**not** on live install). Not sure if this may be still local environment related.

![ft3_install](https://user-images.githubusercontent.com/11295884/38986977-1f7fce1c-43c6-11e8-8f79-281b2ebfa9d4.jpg)

Meantime would mark Visualization issue closed.

Thanks. Should have tested better. Just expect FT to always work, It always has...

T

**Comment by benkeen** [comment]
Ooh interesting about the `notice` error. I'll create a separate ticket about that... thanks!
