### ISSUE TITLE
Problem with "USE IN YOUR PAGE"

### ISSUE THREAD

**Issue by thebitdoctor** [formtools/module-data_visualization#13]
Hello everyone! 
I've a problem whit the module
I copied the php code (from "use in your page" section) and pasted on html page on my website, but nothing happen.

I'm using php 7 (the website and formtools are in the same server)

Thanks

**Comment by benkeen** [comment]
Rats! You're right... let me look this over. It looks like some sort of path issue. Keep you posted.

**Comment by benkeen** [comment]
I'll release a new version containing a patch for this tonight. Thanks for reporting it, @thebitdoctor!

**Comment by thebitdoctor** [comment]
Thanks for your work!

**Comment by thebitdoctor** [comment]
sorry... I still have the same problem... This time I'm going to upload pic!
![1](https://user-images.githubusercontent.com/34324085/38993470-04cd864a-43e4-11e8-9312-a2bc17cd5452.jpeg) 
![2](https://user-images.githubusercontent.com/34324085/38993502-1c47db72-43e4-11e8-992d-96af187605fd.jpeg)

Am I wrong In something? 
Sorry for disturb . TB

**Comment by benkeen** [comment]
No worries! Hmm... did you copy the entire block including the opening `<?php` tag? Since the PHP is just being output to the page it means it's not being interpreted. That either means the PHP wasn't quite right, or the page isn't a PHP page. Possibly the latter?

The code should be good now though - I confirmed it was all working locally.

**Comment by thebitdoctor** [comment]
🤔 I copied all the code, and Pasted it in one embed widget.
It doesn’t work.
So I tried ti include directly in the HTML code but same result

Do you thing could be some setting like mysql, compatibility...?

**Comment by benkeen** [comment]
Sounds like maybe it's not a PHP page? 

Try copying & pasting the following block into your page. It should output "Hello world!" and no other chars. Mind trying it? 

```php
<?php echo "Hello world!"; ?>
```

**Comment by thebitdoctor** [comment]
ok, problem solved!

I copied in a new .php page the php code and redirected the widget code to that page.

Finally it work!!

Thanks for you precious help @benkeen !!!

**Comment by benkeen** [comment]
No problem! Glad it got solved. 😄
