### ISSUE TITLE
Add date range field to Field Charts visualization type

### ISSUE THREAD

**Issue by benkeen** [formtools/module-data_visualization#16]
From here:
https://github.com/formtools/core/issues/403

**Comment by nelsondcosta23** [comment]
hmm works with FT 2.2.6?!

**Comment by NateSchwarz** [comment]
Thanks Ben!

**Comment by wazeefah-formtools** [comment]
Hi
 
Can someone please confirm if the date range functionality is working in Data Visualization - version 2.1.2?

Actually I have created a FIELD CHART visualization. And i want to have the chart based on date - for the last 7 days. In the APPEARANCE tab, I have chosen 'Last 7 Days' for 'Date Range to Display'. However, the right chart is not getting displayed. It's actually taking all the submissions of the form.

Same applies for the other options of date range too, for example, for the 'Last 10 days', 'Last 30 days'. The charts are not dynamically changing based on the date range.

Can someone confirm if this is actually a bug or whether I am missing something, please?

Thanks in advance.
