### ISSUE TITLE
New Field Chart> Error: Not Found

### ISSUE THREAD

**Issue by pourfallah** [formtools/module-data_visualization#2]
hi
i maked an form and now i want to use this module, but its makes `Error: Not Found` error;
i selected `Form `and `View`, but i can't select `Field`.
how i can make and chart from my form?
thanks

**Comment by pourfallah** [comment]
that's happened in the `manage_visualizations.js` at the line: 134 in `url` of ajax query.
you must fix the url with your module correct directory name.

**Comment by pourfallah** [comment]
you must change the folder name of this module to `data_visualization` before install it. this make module installer make correctly.

**Comment by benkeen** [comment]
Sorry about the confusion with the folder names. I've updated all the README's on all repos to include a link to the installation instructions. That page mentions you need to rename the folder names.
