### ISSUE TITLE
Activity Chart bug - Unable to create visualization

### ISSUE THREAD

**Issue by tkelling** [formtools/module-data_visualization#20]
Hello,

I'm unable to create "activity chart" data visualization. Every time I try, I get a 500 error. I can create "field chart" data visualization without this error. 

Since the last time I used this feature without any problem, we have updated to version 3.0 (and now 3.0.10). We also have the current version of the module 2.1.0.

Any suggestions about how to fix this?

Thanks,

Thad

**Comment by tkelling** [comment]
Hi @benkeen, thanks for taking a look at this.

No, I don't get 500 errors on any other page in Form Tools. It only happens when trying to create this type of visualization. It worked fine before upgrading to 3.0 last year. 

Below is my error log in case that helps you.

I tried adding that line to my config.php file. It didn't seem to do anything. The only error I received in my browser was still just the 500 page error.

###########
ERROR LOG
###########

FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/services/web/[my-website-URL]/formtools/modules/data_visualization/templates/activity_charts/add.tpl"  on line 68 "{chart_date_range_dropdown name_id="date_range" default=$module_settings.activity_chart_date_range}" unknown tag "chart_date_range_dropdown" <-- , referer: https://[my-website-URL]/formtools/modules/data_visualization/
[Mon Jan 21 09:50:37.188565 2019] [:error] [pid 122906:tid 140503320315648] [client 155.97.74.165:59352] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr:   thrown in /services/web/[my-website-URL]/formtools/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 68, referer: https://[my-website-URL]/formtools/modules/data_visualization/
[Mon Jan 21 09:50:41.788012 2019] [:error] [pid 122763:tid 140503219603200] [client 155.97.74.165:59356] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/services/web/[my-website-URL]/formtools/modules/data_visualization/templates/activity_charts/add.tpl"  on line 68 "{chart_date_range_dropdown name_id="date_range" default=$module_settings.activity_chart_date_range}" unknown tag "chart_date_range_dropdown" <-- , referer: https://[my-website-URL]/formtools/modules/data_visualization/
[Mon Jan 21 09:50:41.788088 2019] [:error] [pid 122763:tid 140503219603200] [client 155.97.74.165:59356] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr:   thrown in /services/web/[my-website-URL]/formtools/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 68, referer: https://[my-website-URL]/formtools/modules/data_visualization/

**Comment by nelsondcosta23** [comment]
hmm i have a problem to, i think its the same...

When i go to " DOMAIN/modules/data_visualization/activity_charts/add.php "

I have a blank page :S

**Comment by benib596** [comment]
Hi Ben,

Even I too getting the same error.

Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:C:\xampp\htdocs\7servos\modules\data_visualization\templates\activity_charts\add.tpl" on line 68 "{chart_date_range_dropdown name_id="date_range" default=$module_settings.activity_chart_date_range}" unknown tag "chart_date_range_dropdown" <-- thrown in C:\xampp\htdocs\7servos\vendor\smarty\smarty\libs\sysplugins\smarty_internal_templatecompilerbase.php on line 68

**Comment by benkeen** [comment]
Heya, anyone able to give me temporary access to your env to debug this? I don't see why it would occur, honestly, so I kinda need to look at it directly to get an idea of what's going on.

**Comment by benkeen** [comment]
Apologies! This is a bug - I had a modified version I was using locally that didn't have this problem. I'll release an update today that patches this issue. Thanks for giving me access, @nelsondcosta23!
