### ISSUE TITLE
FieldCharts.class.php needs it's filename changed

### ISSUE THREAD

**Issue by agottschling** [formtools/module-data_visualization#5]
When trying to use FormTools on a case sensitive filesystem, whether trying to complete installation or opening the module list, an error will be thrown when the code is trying to find `FieldCharts.class.php`. This is due to the fact that the file is actually named F**I**eldCharts.class.php. Changing the filename to contain a lowercase i fixes the problem.

**Comment by benkeen** [comment]
Ack! I'm sorry about that - I'll do a patch now & it'll be included in the next release. Thanks for letting me know. :)
