### ISSUE TITLE
visualizations in "Pages"  Notice:Undefined index

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-data_visualization#7]
Using "Create Page and Add to Menu" button in "Advanced under edit field chart, I get the below errors when I go to the page created. 
The smarty syntax created in the page was:
<div style="border:1px solid #cccccc">
    {template_hook location="data_visualization" vis_id=1 height=400 width=738}
</div>

Notice: Undefined index: label in /var/www/forms.buffalonews.com/modules/data_visualization/code/Visualizations.class.php on line 354

Notice: Undefined index: data in /var/www/forms.buffalonews.com/modules/data_visualization/code/Visualizations.class.php on line 355

Notice: Undefined index: label in /var/www/forms.buffalonews.com/modules/data_visualization/code/Visualizations.class.php on line 354

Notice: Undefined index: data in /var/www/forms.buffalonews.com/modules/data_visualization/code/Visualizations.class.php on line 355

Notice: Undefined index: label in /var/www/forms.buffalonews.com/modules/data_visualization/code/Visualizations.class.php on line 354

Notice: Undefined index: data in /var/www/forms.buffalonews.com/modules/data_visualization/code/Visualizations.class.php on line 355

**Comment by johnbleck3** [comment]
![1-22-2018 9-20-21 pm](https://user-images.githubusercontent.com/12632568/35254855-1c79d960-ffba-11e7-9a13-5fc7b79af997.png)

**Comment by johnbleck3** [comment]
I also noticed in the JS Error logs -  occured when I was testing this

![1-22-2018 9-58-40 pm](https://user-images.githubusercontent.com/12632568/35255953-7ffedbe8-ffbf-11e7-9f8e-974ee3ee2e21.png)

**Comment by benkeen** [comment]
Great, thanks! I'll take a look this week.

**Comment by benkeen** [comment]
Fixed in 2.0.5.
